### PR TITLE
Upgrade Fullcallendar to 2.4.0

### PR DESCRIPTION
**Pull request by maxime-lenne**
Hi,

Pull request to upgrade to FullCalendar 2.4.0 for issue #48

### CODE REVIEW

**Comment by maxime-lenne** [comment]
Yes I  have make a mistake in my commit message...

**Comment by gr8bit** [comment]
@maxime-lenne did you use the original full calendar-release without reformatting it? it shows many whitespace-diffs, that's why I ask. We only intend to repackage the raw, unedited fullcalendar-releases.

**Comment by maxime-lenne** [comment]
@gr8bit Yes i have used the original full calendar-release without reformating.

**Comment by gr8bit** [comment]
Updated to 2.4.0, thank you!

**Comment by gr8bit** [comment]
Released 2.4.0.1 (important fix, 2.4.0.0 included old fullcalendar.js) and 2.4.0.2 (added new dependency on jquery-ui - let me know if you have problems)

**Pull request closed without merging**
