### PR TITLE
Fullcalendar 3.1.0

### PR DESCRIPTION
**Pull request by davidwessman**

### CODE REVIEW

**Comment by davidwessman** [comment]
@gr8bit Do you have time to merge this? 🙂

**Comment by gr8bit** [comment]
Whoooooa sorry David, forgot about it. Shame on me!

**Comment by davidwessman** [comment]
No worries 🙂 Wasn't sure if you had seen it or not !🙂

**Comment by gr8bit** [comment]
Pushed. :)

**Pull request merged**
