### PR TITLE
Update to Fullcalendar 3.0.0

### PR DESCRIPTION
**Pull request by brendon**

### CODE REVIEW

**Comment by brendon** [comment]
Addresses #69 

You're not doing anything tricky in the js file right? Just a straight copy and paste? That's what I've done.

**Comment by brendon** [comment]
Fixed that. The github editor adds an empty last line.

**Comment by davidwessman** [comment]
@gr8bit 😄

**Comment by haslo** [comment]
Absolutely perfect timing folks, I was just now looking for implementing a thing with fullcalendar that's available for 17 days now with 3.0 😁

**Comment by gr8bit** [comment]
You guys rock.

**Comment by brendon** [comment]
Thanks :) Yes looking forward to the new features. The list feature looks great!

**Comment by brendon** [comment]
Just wondering if you could tag and release a new gem version?

**Pull request merged**
